### PR TITLE
Fixes GridView pagination issue

### LINKED ISSUE #56: Fix number of item show on Gridview when only one item is returned
Gridview shows the total item number equals to 0 when only one element is returned
Example : Showing 1-1 of 1 item. instead of Showing 1-1 of 0 item.

### PR DESCRIPTION
**Pull request by niio972**
Fixes #56

### CODE REVIEW

File: models/wsModels/WSActiveRecord.php [hunk 1]
```diff
@@ -113,6 +110,11 @@ public function find($sessionToken, $attributes) {
             $this->totalCount = $requestRes->{WSConstants::METADATA}->{WSConstants::PAGINATION}->{WSConstants::TOTAL_COUNT};
             $this->page = $requestRes->{WSConstants::METADATA}->{WSConstants::PAGINATION}->{WSConstants::CURRENT_PAGE};
             $this->pageSize = $requestRes->{WSConstants::METADATA}->{WSConstants::PAGINATION}->{WSConstants::PAGE_SIZE};
+        }else{
```
Comment (annetireau) [inline models/wsModels/WSActiveRecord.php]: space
